# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-18 17:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WishListApp1', '0002_auto_20191018_2229'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishdata',
            old_name='ftdate',
            new_name='wishDatetobuy',
        ),
    ]
