# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-19 06:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WishListApp1', '0003_auto_20191018_2245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishdata',
            name='wishnum',
        ),
    ]
